# development docker-compose file
version: '0.1'

services:

  scraper:
    image: public.ecr.aws/unocha/hdx-scraper-scrapername:0.1
    volumes:
      - "./:/srv"
    working_dir: /srv
    command: ./run-dev.sh
    env_file:
      - run_env
